### ISSUE TITLE
[feat] HomeTaskDetail 기능 및 Category 레이아웃

### ISSUE THREAD

**Issue by seoyoon513** [TaskerPM/Tasker-Android#11]
# Description
상세화면 기능 및 카테고리 레이아웃 그리기

# Todo 
- [x] 노트 추가 및 삭제
- [x] 작성 중 뒤로가기 시 Dialog 띄우기
- [x] 시간 설정 Bottom Sheet
- [x] 잘못된 시간 설정 시 Dialog 띄우기
- [x] 카테고리 화면
- [x] 카테고리 추가 화면
