### ISSUE TITLE
[feat] Add Modules, Network, DI

### ISSUE THREAD

**Issue by dongk00** [TaskerPM/Tasker-Android#2]
# Description 

1. Module 분리

데이터 추가 : data, domain module 추가 및 파일 분리
Domain - Usecase 추후에 추가

2. Network

Server API 연결
retrofit, okhttp3로 server api 연결 및 test 진행

3. Dependency Injection

Hilt 도입

# Todo

- [x] Add data, domain modules
- [x] connect server api
- [x] hilt - retrofit, repository, dispatchers, api ...
