### ISSUE TITLE
[layout] Home Layout

### ISSUE THREAD

**Issue by dongk00** [TaskerPM/Tasker-Android#8]
# Description

Home Layout 그리기
RecyclerView는 dummy data로 진행
기본형 & 카테고리형 진행 (시간형 뷰는 이후에)

API 연동 후 feature 재작업 필요

# Todo 

- [x] 홈 일주일 단위 캘린더 View
- [x] bottomsheet 캘린더 View
- [x] 기본형 View
- [x] 기본형 View Feature
- [x] 카테고리형 View
- [x] 카테고리형 View Feature
- [x] Bottom Navigation 동작 fix

**Comment by dongk00** [comment]
## Issue 정리

### textSize
전체적인 textsize가 작게 나옴
서윤님 기기 : Datepicker 숫자 textSize가 아래로 내려가거나 잘림.
datpicker item 갯수는 7개로 고정되어 있으므로 textSize에 의한 크기 변동은 불가하다. 해결방법 모색할 것.

### recyclerview binding
item의 data는 잘 받아오나 뷰에 랜덤으로 바뀌어서 뿌려지는 경우가 많음.
item 재사용 시 bind 문제로 보임 !

### manifest windowSoftInputMode = "AdjustResize" 
화면마다 디자인에 맞게 값 변경할 것
올라오지 않는 View들 체크할 것

### tablayout 위아래 padding
사소함
tablayout의 양옆 padding은 조절할 수 있으나 위아래 padding 조절이 안됨. default padding이 조금 있어서 다른 뷰들과의 간격이 더 크게 보일 수 있음.
